# https://www.playframework.com/documentation/latest/Configuration
db.default.driver   = com.mysql.cj.jdbc.Driver
db.default.url      = "jdbc:mysql://localhost:3306/football_club?useSSL=false&serverTimezone=UTC"
db.default.username = "tdp_user"
db.default.password = "tdp_passwd"
play.evolutions.db.default.autoApply = true
play.filters.disabled += "play.filters.csrf.CSRFFilter"

